//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoDealer.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Automoviles
    {
        public int Id { get; set; }
        public int Suplidor { get; set; }
        public Nullable<int> Liquidaciones { get; set; }
        public Nullable<int> Factura { get; set; }
        public int Showroom { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public System.DateTime Year { get; set; }
        public System.DateTime FechaEntrada { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
        public int Status { get; set; }
        public int TipoAutomovil { get; set; }
        public Nullable<int> PrecioVenta { get; set; }
        [StringLength(20)]
        public string Placa { get; set; }
        [StringLength(20)]
        public string Vin { get; set; }
        public Nullable<int> PrecioMinimo { get; set; }
        public Nullable<int> Costo { get; set; }
        [StringLength(20)]
        public string Referencia { get; set; }
        public Nullable<int> Color { get; set; }
    
        public virtual Automoviles Automoviles1 { get; set; }
        public virtual Automoviles Automoviles2 { get; set; }
        public virtual Colores Colores { get; set; }
        public virtual Facturas Facturas { get; set; }
        public virtual Liquidaciones Liquidaciones1 { get; set; }
        public virtual Showrooms Showrooms { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual TiposAutomoviles TiposAutomoviles { get; set; }

        public static Automoviles GetAutomovil(int Id)
        {
            AutoDealerEntities db = new AutoDealerEntities();
            Automoviles Automovil = db.Automoviles.Find(Id);
            return Automovil;
        }

        /// <summary>
        /// Retorna todos los años existentes y distintos (campo Year) para todos los Automoviles.
        /// </summary>
        /// <param name="Id">El Id del Automovil.</param>
        /// <returns></returns>
        public static List<DateTime> GetAllYears()
        {
            AutoDealerEntities db = new AutoDealerEntities();
            List<DateTime> AutomovilesYears = new List<DateTime>();
            AutomovilesYears = (from a in db.Automoviles select a.Year).Distinct().OrderByDescending(x => x.Year).ToList();
            return AutomovilesYears;
        }

        /// <summary>
        /// Retorna todos los Automoviles de un año en especifico.
        /// </summary>
        /// <param name="Id">El Año del Automovil.</param>
        /// <returns></returns>
        public static List<Automoviles> GetAutomovilOfYear(string Year)
        {
            DateTime Year2;
            Year2 = DateTime.Parse(Year);
            AutoDealerEntities db = new AutoDealerEntities();
            List<Automoviles> Automoviles = new List<Automoviles>();
            Automoviles = db.Automoviles.Where(x => x.Year == Year2).ToList();
            return Automoviles;
        }
    }
}
