//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
namespace AutoDealer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compradores
    {
        public Compradores()
        {
            this.Facturas = new HashSet<Facturas>();
        }
    
        public int Id { get; set; }
        [Required]
        public string Nombre { get; set; }
        [Required]
        public string Apellido { get; set; }
        [StringLength(12)]
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        [StringLength(12)]
        public string Celular { get; set; }
        public string Email { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public int Status { get; set; }
    
        public virtual ICollection<Facturas> Facturas { get; set; }
    }
}
