//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoDealer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturasDetalles
    {
        public int Id { get; set; }
        public int Factura { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Precio { get; set; }
        public Nullable<int> Descuento { get; set; }
    
        public virtual Facturas Facturas { get; set; }
    }
}
