//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoDealer.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    public partial class Facturas
    {
        public Facturas()
        {
            this.Automoviles = new HashSet<Automoviles>();
        }
    
        public int Id { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public int Vendedor { get; set; }
        public int Comprador { get; set; }
        public string NCF { get; set; }
        public Nullable<int> CostoTraspaso { get; set; }
        public Nullable<int> Empresa { get; set; }
        public Nullable<int> Descuento { get; set; }
    
        public virtual ICollection<Automoviles> Automoviles { get; set; }
        public virtual Empresas Empresas { get; set; }
        public virtual Personas Personas { get; set; }
        public virtual Personas Personas1 { get; set; }

        public static Facturas GetFactura(int Id)
        {
            AutoDealerEntities db = new AutoDealerEntities();
            Facturas Factura = new Facturas();
            Factura = db.Facturas.Where(x => x.Id == Id).FirstOrDefault();
            return Factura;
        }

        public static Facturas GetFactura(string Id)
        {
            int IdInt = Int32.Parse(Id);
            AutoDealerEntities db = new AutoDealerEntities();
            Facturas Factura = new Facturas();
            Factura = db.Facturas.Where(x => x.Id == IdInt).FirstOrDefault();
            return Factura;
        }

        public static List<Facturas> GetFacturaInDateRange(DateTime Desde, DateTime Hasta)
        {
            AutoDealerEntities db = new AutoDealerEntities();
            List<Facturas> ListaFacturas = new List<Facturas>();
            ListaFacturas = (from a in db.Facturas where (a.FechaCreacion >= Desde && a.FechaCreacion <= Hasta) select a).ToList();
            return ListaFacturas;

        }
    }
}
