//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoDealer.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    public partial class PersonasRoles
    {
        public int Id { get; set; }
        public int Persona { get; set; }
        public int Rol { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<double> Comision { get; set; }
    
        public virtual Personas Personas { get; set; }
        public virtual TiposRoles TiposRoles { get; set; }

        public static string GetComision(int Id)
        {
            AutoDealerEntities db = new AutoDealerEntities();
            PersonasRoles PersonaRole = new PersonasRoles();
            PersonaRole = db.PersonasRoles.Where(x => x.Id == Id).First();
            return PersonaRole.Comision.ToString();
        }

        public static string GetComsision(string Id)
        {
            int IdInt = Int32.Parse(Id);
            AutoDealerEntities db = new AutoDealerEntities();
            PersonasRoles PersonaRole = new PersonasRoles();

            PersonaRole = db.PersonasRoles.Where(x => x.Id == IdInt).First();
            return PersonaRole.Comision.ToString();
        }
    }
}
