//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoDealer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Showrooms
    {
        public Showrooms()
        {
            this.Automoviles = new HashSet<Automoviles>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int Empresa { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual ICollection<Automoviles> Automoviles { get; set; }
        public virtual Empresas Empresas { get; set; }
    }
}
