//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoDealer.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    public partial class Showrooms
    {
        public Showrooms()
        {
            this.Automoviles = new HashSet<Automoviles>();
        }

        public static Showrooms GetShowroom(int Id)
        {
            AutoDealerEntities db = new AutoDealerEntities();
            Showrooms Lista = new Showrooms();
            Lista = db.Showrooms.Where(Showroom => Showroom.Id == Id).First();
            return Lista;
        }

        /// <summary>
        /// Este metodo retorna un modelo, dado un fabricante.
        /// </summary>
        /// <param name="Fabricante">El Id del fabricante.</param>
        /// <returns></returns>
        public static List<Showrooms> GetAllShowrooms()
        {
            AutoDealerEntities db = new AutoDealerEntities();
            List<Showrooms> Lista = new List<Showrooms>();
            Lista = db.Showrooms.Distinct().ToList();
            return Lista;
        }

        /// <summary>
        /// Este metodo retorna un modelo, dado un fabricante.
        /// </summary>
        /// <param name="Fabricante">El Id del fabricante.</param>
        /// <returns></returns>
        public static List<Showrooms> GetShowrooms(int Empresa)
        {
            AutoDealerEntities db = new AutoDealerEntities();
            List<Showrooms> Lista = new List<Showrooms>();
            Lista = db.Showrooms.Where(Showroom => Showroom.Empresa == Empresa).ToList();
            return Lista;
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int Empresa { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual ICollection<Automoviles> Automoviles { get; set; }
        public virtual Empresas Empresas { get; set; }
        public virtual Status Status1 { get; set; }
    }
}
