//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoDealer.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class TiposAutomoviles
    {
        public TiposAutomoviles()
        {
            this.Automoviles = new HashSet<Automoviles>();
        }

        public static int GetTipoAutomovil(string Fabricante, string Modelo)
        {
            int TipoAutomovil;
            int FabricanteInt = Int32.Parse(Fabricante);
            int ModeloInt = Int32.Parse(Modelo);
            AutoDealerEntities db = new AutoDealerEntities();
            List<TiposAutomoviles> ListaTiposAutomoviles = new List<TiposAutomoviles>();
            ListaTiposAutomoviles = db.TiposAutomoviles.Where(x => x.Fabricante == FabricanteInt).ToList();
            ListaTiposAutomoviles = ListaTiposAutomoviles.Where(x => x.Modelo == ModeloInt).ToList();
            return TipoAutomovil = ListaTiposAutomoviles.First().Id;
        }

        /// <summary>
        /// Retorna el Fabricante y Modelo dado un Automovil.
        /// </summary>
        /// <param name="Fabricante">El Id del Automovil.</param>
        /// <returns></returns>
        public static String NombreTipoAutomovil(int Automovil)
        {
            AutoDealerEntities db = new AutoDealerEntities();

            List<Automoviles> ListaAutomoviles = new List<Automoviles>();
            ListaAutomoviles = db.Automoviles.Where(x => x.Id == Automovil).ToList();

            int TipoAutomovil = ListaAutomoviles[0].TipoAutomovil;
            List<TiposAutomoviles> ListaTiposAutomoviles = new List<TiposAutomoviles>();
            ListaTiposAutomoviles = db.TiposAutomoviles.Where(y => y.Id == TipoAutomovil).ToList();

            List<Fabricantes> Fabricante = Fabricantes.GetFabricante(ListaTiposAutomoviles[0].Fabricante);
            List<Modelos> Modelo = Modelos.GetModelo(ListaTiposAutomoviles[0].Modelo);

            string Nombres = Fabricante[0].Nombre + " " + Modelo[0].Nombre;
            return Nombres;
        }

        public int Id { get; set; }
        public int Fabricante { get; set; }
        public int Modelo { get; set; }
        public Nullable<int> Trim { get; set; }
        public int Status { get; set; }

        public virtual ICollection<Automoviles> Automoviles { get; set; }
        public virtual Fabricantes Fabricantes { get; set; }
        public virtual Modelos Modelos { get; set; }
        public virtual Trim Trim1 { get; set; }
    }
}